version: "3.8"

services: 
  accounts:
    image: spring-cloud/accounts:latest
    mem_limit: 700m
    ports: 
      - "8080:8080"
    networks: 
      - spring-cloud-network
  loans:
    image: spring-cloud/loans:latest
    mem_limit: 700m
    ports: 
      - "8090:8090"
    networks: 
      - spring-cloud-network
  cards:
    image: spring-cloud/cards:latest
    mem_limit: 700m
    ports: 
      - "9000:9000"
    networks: 
      - spring-cloud-network

networks: 
  spring-cloud-network: